### MEMÓRIA DEFINITIVA 1: O Início

POST   http://127.0.0.1:5000/api/vlog-posts
Content-Type: application/json

{
    "titulo": "O Primeiro Contato: Eu curti você!",
    "texto": "Esse foi o dia em que a gente se falou pela primeira vez. Você estava na aula de Física e eu, na de Sociologia. Você saiu para ir ao banheiro e, por sorte, eu estava fora da sala. Fui até o corredor perto do banheiro te esperar — como se o destino tivesse dado um empurrãozinho. Quando você passou, eu te parei e falei: “Eu curti você!” Pedi seu Instagram, você me passou e voltou para a sala. Naquele momento, eu tive certeza: era você. No fim da aula, te levei até a parada de ônibus. Você não parava de falar (kkk), e eu só conseguia pensar em como seu jeito era encantador. Antes de você subir no ônibus, me deu um abraço e um beijo na bochecha. E foi ali, naquele instante simples e mágico, que eu me apaixonei por você. ❤️",
    "data_do_momento": "2025-08-18T20:47:00", 
    "link_midia":""
}

### Primeiro Beijo 

POST  http://127.0.0.1:5000/api/vlog-posts
Content-Type: application/json

{
    "titulo": "Nosso Primeiro Beijo",
    "texto": "Nosso primeiro beijo aconteceu no mesmo dia em que conheci sua mãe. A gente ainda não namorava e nem sabia ao certo se iria ficar. Estávamos na parada de ônibus, conversando sobre coisas bobas, rindo à toa, até o ônibus chegar. Sua mãe entrou primeiro e, de repente, você veio me abraçar. Sem pensar duas vezes, eu te puxei e te beijei. Eu estava nervoso, o coração disparado, mas aquele momento parecia o certo — o nosso momento. Você ficou toda envergonhada, sem reação, e saiu correndo para subir no ônibus (kkk). E assim foi o segundo momento especial no começo da nossa história — o beijo que marcou o início de tudo. ❤️",
    "data_do_momento": "2025-08-19T22:00:00",
    "link_midia": ""
}