### POST: Foto 1 - Primeira foto juntos

POST  http://127.0.0.1:5000/api/album-photos
Content-Type: application/json

{
    "titulo": "Primeira Selfie Juntos",
    "descricao": "Nossa primeira selfie oficial!",
    "url_foto": "https://i.postimg.cc/gkP579SZ/primeirafoto.jpg",
    "album_id": 1
}

### POST: Foto 2 - foto depois do cinema

POST http://127.0.0.1:5000/api/album-photos
Content-Type: application/json

{
    "titulo": "Foto Depois do Cinema",
    "descricao": "Depois de assistimos Invocação do Mal 4 juntos.",
    "url_foto": "https://i.postimg.cc/XvCFyPwP/fotodepoisdocinema.jpg",
    "album_id": 2
}